name: test-deployment

on:
  push:
    branches:
      - dev

# Allow one concurrent deployment
concurrency:
  group: "gh-pages-test"
  cancel-in-progress: true

env:
  # Hosted GitHub runners have 7 GB of memory available, let's use 6 GB
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  test-deploy:
    name: test-deploy
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x.x]
          # https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        id: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        id: install
        run: yarn install --frozen-lockfile

      - name: Build
        id: build
        run: yarn build

  deploy-to-main:
    name: deploy-to-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge dev -> main
        id: merge
        uses: everlytic/branch-merge@1.1.2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
          target_branch: main
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}